### ISSUE TITLE
[Não Conformidade] Inexistência do Plano de Medição

### ISSUE THREAD

**Issue by Matheusss03** [UnbFeelings/unb-feelings-docs#14]
@UnbFeelings/process 

Perante critérios definidos para as [Auditorias](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria) fora auditado os [Testes de Software](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-de-Testes-de-Software---Ciclo-1) da equipe de *Desenvolvimento* seguindo os padrões definidos no Plano de Medição proposto pela equipe de *Processo*.

### Descrição

Após a realização de um Checklist no repositório do produto fora notado que alguns testes estão sendo feitos porém sem o direcionamento do Plano de Medição feito pela equipe de Processo, já que o mesmo não existe.

### Recomendação

Para que o produto em desenvolvimento seja feito com qualidade é preciso que um Plano de Medição associado seja feito e acompanhado pela equipe de Processo.

#### Detalhes

**Auditor**: Matheus Figueiredo
**Técnica de Audição**: Checklist
**Data da Audição**: 16/04/2018

**Comment by ulyssesBML** [comment]
Foi realizado no dia 16/04 

link: [plano](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Plano-de-Medi%C3%A7%C3%A3o)
