### ISSUE TITLE
Necessidades da Equipe de GQA

### ISSUE THREAD

**Issue by joaopaulonsoares** [UnbFeelings/unb-feelings-docs#2]
Para realizar a auditoria da melhor forma possível, precisamos saber de algumas coisas que o processo não deixa claro como será realizado.

- [ ] Onde os produtos gerados pelo processo serão armazenados ? Wiki, Drive ?
- [ ] Como será a estrutura desses artefatos de saída (produtos)? Por exemplo: Qual a estrutura do _backlog_ ? O que esse _backlog_ vai conter e como ? ( Um template que deve ser seguido );
- [ ] Precisamos que o GQM seja definido o quanto antes;
- OBS: Qualquer dúvida, criem uma _issue_ no nosso repositório.

**Comment by eliseuegewarth** [comment]
@UnbFeelings/process
