### ISSUE TITLE
[Não Conformidade] Relatório Final não existe

### ISSUE THREAD

**Issue by JonathanRufino** [UnbFeelings/unb-feelings-docs#25]
@UnbFeelings/process  

Perante critérios definidos para as [Auditorias](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#plano-de-medi%C3%A7%C3%A3o) fora auditada o artefato Relatório Final, resultante da atividade [Relatório Final de Medição](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#317-atividade-relatório-final-de-medição).

### Descrição

Foi identificado que não foram realizadas coletas de métricas de código fonte, ou se foram, não estão descritas em um artefato de acordo com o proposto pelo processo.

#### Recomendações

É recomendado a integração de ferramentas de análise de código para que as métricas possam ser geradas automaticamente, sem que haja a necessidade de atribuir esta tarefa a uma pessoa. No entanto recomenda-se definir um responsável pela elaboração do relatório de métricas.

#### Detalhes

**Auditor**: Jonathan Rufino
**Técnica de Audição**: Checklist
**Tipo:** Medição e Análise
**Prazo:** 23/04/2018

**Comment by ulyssesBML** [comment]
Você está falando do relatório de desempenho? Porque o relatório final que está descrito no processo  só é gerado no final do semestre.

**Comment by Rdlenke** [comment]
@ulyssesBML Você tem razão, este objeto não deveria ser auditado, já que a equipe de desenvolvimento não chegou no fim do semestre.

Estou fechando a issue.
