### ISSUE TITLE
[Não Conformidade] Lista informal de requisitos

### ISSUE THREAD

**Issue by AllanNobre** [UnbFeelings/unb-feelings-docs#26]
@UnbFeelings/devel 

A auditoria da [Lista Informal de Requisitos](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2211-elicitar-requisitos) foi feita com base nos [critérios](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#lista-informal-de-requisitos) pré-estabelecidos para poder verificar se a atividade Elicitar Requisitos aconteceu. O resultado da auditoria pode ser acessado através da seguinte página: [Lista Informal de Requisitos](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-Lista-informal-de-requisitos---Ciclo-1).

_Observação: Não é possível delimitar prazo para a correção, já que a fase de requisitos do ciclo já foi realizada._ 

### Descrição

O Artefato, Lista Informal de Requisitos, planejado no processo não foi criado ou documentado pela equipe de desenvolvimento.

#### Recomendações

Procurar trazer o cliente para dentro do processo de desenvolvimento o máximo possível, já que essa fase inicial de requisitos foi afetada pela falta desse artefato previsto no processo.

### Detalhes

**Autor:** Allan Nobre
**Tipo:** Subprocesso de Requisitos, atividade Elicitar Requisitos
**Prazo:** Seria de 1 dia para a correção, pela Matriz GUT, mas não cabe correção para esse caso

**Comment by ThalissonMelo** [comment]
Decidimos que este documento é informal de mais para ser documentado, portanto não está mais descrito como um documento de saída do processo

**Comment by AllanNobre** [comment]
Ótimo! Isso já representa uma melhoria do processo! Bom trabalho!
