### ISSUE TITLE
Processo de requisitos aparece diversas vezes com a mesma descrição

### ISSUE THREAD

**Issue by Rdlenke** [UnbFeelings/unb-feelings-docs#3]
Olá a todos. 

Estava analisando o processo pra poder identificar os artefatos a serem auditados e os critérios de avaliação e cheguei num problema. No processo da área de desenvolvimento, a primeira atividade é o -**subprocesso de requisitos**.  Este subprocesso tem como resultado um Backlog, que entra no planejamento da release. O resultado do planejamento da release vai pro subprocesso de desenvolvimento, que novamente, chama o **subprocesso de requisitos**. 

Ambos esses processos de requisito tem exatamente a mesma descrição, mas aparecem em momentos diferentes do processo. Qual a diferença entre eles?

**Comment by MatheusRich** [comment]
Olá @Rdlenke (@UnbFeelings/gqa),

O *subprocesso de requisitos* é um processo "genérico". Ele é aplicado duas vezes no projeto mas em níveis de abstração diferentes:

* No item *2.0.1.1.* são coletados requisitos a nível de Release (épicos, features). 
* No item *2.1.1.1.* são coletados requisitos a nível de Sprint (histórias, tasks).

Como são bastante parecidos, optamos por fazer esta abstração para não repetir o diagrama.

Dei uma pequena atualizada nos textos para tentar deixar isso mais claro. Alguma sugestão?

**Comment by Rdlenke** [comment]
Tudo bem, eu consegui compreender a diferença na abstração. Obrigado.
