### ISSUE TITLE
Modelo Ideal - Fase de Inicialização

### ISSUE THREAD

**Issue by Rdlenke** [UnbFeelings/unb-feelings-docs#30]
Issue para controle dos estudos do modelo IDEAL, focando na fase de inicialização definida pelo mesmo.
Os resultados parciais deste estudo podem ser colocados nos comentários das issues, para serem consolidados depois num documento formal.

Todos os integrantes da equipe de processo do segundo ciclo estão alocados

@UnbFeelings/themis

**Comment by AllanNobre** [comment]
@Rdlenke A professora colocou um material no Moodle que pode nos ajudar! É um bom começo nos estudos!
