### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by maugustoo** [UnbFeelings/unb-feelings-docs#31]
O propósito desta atividade é organizar a equipe de melhoria de processos para montar uma proposta para o gerenciamento para o lançamento de um programa de melhoria de processo.

Tarefas:

- [x] Identificar e descrever os departamentos que serão partes interessadas no programa de melhoria de processo software.
- [x] Descrever a abordagem que será utilizada para para conduzir o programa de melhoria de processo de software. (Modelo IDEAL)
- [x] Identifique as necessidades de negócios.

**Comment by maugustoo** [comment]
É interessante ler a fase 1.1 do modelo ideal Getting Started, que descreve alguns passos para se conseguir atingir os objetivos descritos.

Para facilitar eu comecei a fazer uma tradução dos primeiros passos da inicialização:
https://docs.google.com/document/d/1WLipOaE--jFkOI6jX4eipKXxGEpwsk2_z2TWPUw-_xI/edit

**Comment by naiieandrade** [comment]
- _Identificar e descrever os departamentos que serão partes interessadas no programa de melhoria de processo software._

A empresa possui três equipes de trabalho maiores, que são os desenvolvedores, a equipe de processo e a equipe de qualidade. Todos eles são partes interessadas no programa de melhoria, juntamente com a alta direção e o cliente. 
A alta direção é responsável pela empresa, por sua organização e funcionamento em geral. É responsável por aprovar ou rejeitar as entregas feitas pelos times, propor mudanças e avaliar todos.
O cliente fornece informações sobre o produto que será desenvolvido, valida as entregas.
Cada equipe possui responsabilidades específicas:    
- Os desenvolvedores são responsáveis pelo desenvolvimento da aplicação.
- A equipe de processo é realiza melhorias do processo, e responsável por seguir os processos e por sua modelagem.
- A equipe de qualidade verifica a qualidade do produto e dos processos.

**Comment by maugustoo** [comment]
No contexto da disciplina Melhoria de Processo de Software foi estabelecido uma relação Organização (Empresa GoHorse+) x Cliente (Jhonatan). Neste contexto há um contrato a ser seguido (Plano de Ensino) e este prevê a divisão da Organização em 3 grandes áreas (Processos, Desenvolvimento e GQA), e estas devem trabalhar de forma orgânica e entregar um produto ao fim dos ciclos.

A empresa é então dividida em três equipes de trabalho, que são os desenvolvedores, a equipe de processo e a equipe de qualidade. Todos eles são partes interessadas no programa de melhoria, juntamente com a alta direção e o cliente.

A alta direção é responsável pela empresa, por sua organização e funcionamento em geral. É responsável por aprovar ou rejeitar as entregas feitas pelos times, propor mudanças e avaliar todos.
O cliente fornece informações sobre o produto que será desenvolvido, valida as entregas. Cada equipe possui responsabilidades específicas:

Razões de negócio:

1) A utilização da metodologia é um facilitador na entrega do produto.
2) A entrega do produto garante um retorno financeiro/INDICADORES (NOTAS) bons à Organização.
3) Discussões sobre melhorias podem facilitar tarefas que causam repulsa por parte das pessoas.
4) Melhorias propostas servirão como insumos para as novas Organizações (Outras turmas de MPS)

Créditos: @freemanpivo

**Comment by maugustoo** [comment]
Abordagem de Melhoria utilizada

Durante um programa de melhoria de processo de software é importante seguir um modelo para ter um rumo e conseguir ter melhores resultados durante a execução deste programa. No contexto da matéria de Melhoria de Processo de Software foi designado ao grupo utilizar o modelo IDEAL (Initiating-Diagnosing-Establishing-Acting-Learning).

O modelo IDEAL

O modelo IDEAL, é um modelo para Melhoria de Processo de Software, desenvolvido pelo Software Engineering Institute. Ele descreve um modelo de programa de melhoria de processos de software (SPI), que pode ser usado para orientar o desenvolvimento de um plano integrado de longo alcance para iniciar e gerenciar um programa SPI. Como material bibliográfico o trabalho vai user o (MCFEELEY, Bob. IDEAL SM: A User’s Guide for Software Process Improvement) que tem o objetivo de fornecer aos gerentes de melhoria de processos uma descrição genérica de uma seqüência de etapas recomendadas para o SPI.
O modelo IDEAL, descreve cinco fases (Fígura 1) de uma iniciativa de SPI que fornecem um loop contínuo através das etapas necessários para o SPI. 

![mps](https://user-images.githubusercontent.com/18356890/39738983-cf15f0f2-5264-11e8-8778-96ba647316d6.jpeg)
Fígura 1 - O modelo IDEAL Fonte: Slide da professora

Iniciação (Initiating) - 

A fase de iniciação do modelo IDEAL é o ponto de partida. Aqui é onde a infra-estrutura de melhoria inicial é estabelecida, e suas funções e responsabilidades são definidas e os recursos iniciais são atribuídos. Nessa fase, um plano SPI é criado para orientar a organização durante as fases de inicialização, diagnóstico e estabelecimento.

Os objetivos gerais do programa SPI são definidos durante a fase de iniciação. Eles são estabelecidos a partir das necessidades de negócios da organização e serão aperfeiçoados e tornados específicos durante a fase de estabelecimento do IDEAL.

Diagnóstico (Diagnosing) -

A fase de Diagnóstico do modelo IDEAL inicia a organização no caminho da melhoria contínua do processo de software. Nessa fase, o plano de ação da SPI é iniciado de acordo com a visão da organização, plano estratégico de negócios, lições aprendidas de trabalhos de melhoria no passado, principais problemas de negócios enfrentados pela organização e metas de longo prazo. 

Estabelecimento (Establishing) - 

Durante a fase de estabelecimento, ocorre a priorização das atividades de melhoria e se criam estratégias para buscar as soluções. O esboço do plano de ação da SPI será concluído de acordo com a visão da organização, plano estratégico de negócios, lições aprendidas de trabalhos de melhoria no passado, principais problemas de negócios enfrentados pela organização e metas de longo prazo.

Durante a fase de estabelecimento, metas mensuráveis ​​são desenvolvidas a partir dos objetivos gerais definidos na fase de iniciação. Essas metas mensuráveis ​​serão incluídas na versão final do plano de ação da SPI.

Por fim, são definidas métricas para se monitorar o processo.

Ação (Acting) - 

Na fase de Ação do modelo IDEAL, as soluções para abordar as áreas de melhoria descobertas durante a fase de Diagnóstico são criadas, testadas e implantadas em toda a organização. Serão desenvolvidos planos para executar pilotos para testar e avaliar os processos novos ou aprimorados. 

Lições (Learning) - 

O objetivo desta fase é tornar a próxima passagem pelo modelo IDEAL mais eficaz. As soluções foram desenvolvidas, as lições foram aprendidas e as métricas de desempenho e realização de metas foram coletadas. Esses artefatos se tornarão uma fonte de informações para o pessoal envolvido na próxima passagem pelo modelo.

Usando essas informações coletadas, uma avaliação da estratégia, métodos e infraestrutura usada no programa SPI pode ser realizada. Ao fazer isso, correções ou ajustes na estratégia, métodos ou infraestrutura podem ser feitos antes do início.

**Comment by maugustoo** [comment]
Fase de iniciação

![iniciacao](https://user-images.githubusercontent.com/18356890/39739994-08923aac-526a-11e8-9eba-0870ea1c71fe.jpeg)

Figura vai ser necessária para explicarmos o que fizemos, o porquê fizemos e onde estamos.

**Comment by naiieandrade** [comment]
- _Descrever a abordagem que será utilizada para para conduzir o programa de melhoria de processo de software. (Modelo IDEAL)_

A abordagem que será utilizada é o modelo IDEAL. É um modelo desenvolvido pelo _SEI - Software Engineering Institute_, no qual define ações para capacitar as organizações a fim de melhorar seus processos.

**Inicialização**: Preparação das bases necessárias para que o esforço de melhoria de processos seja bem sucedido.
**Diagnóstico**: Levantamento do estado atual e definição do estado desejado.
**Estabelecimento**: Planejamento detalhado de como alcançar as melhorias desejadas.
**Ação**: Execução do planejamento.
**Lições**: Aprendizado adquirido durante o processo de melhoria.
