### ISSUE TITLE
Identificar as necessidades de negócios

### ISSUE THREAD

**Issue by maugustoo** [UnbFeelings/unb-feelings-docs#32]
O propósito desta issue é entender, de uma perspectiva de gerenciamento, as principais necessidades de negócios que impulsionam a necessidade de um programa de melhoria de processo de software.

Tarefas:

- [x] Identificar as principais necessidades de negócios que geram motivos para se fazer um programa de melhoria de processo de software.
- [x] Vincule o programa de melhoria de processo de software às necessidades de negócios.
- [x] Fazer uma descrição de alto nível do estado desejado de melhoria de processo.

**Comment by maugustoo** [comment]
É interessante ler a fase 1.2 do modelo ideal, que descreve alguns passos para se conseguir atingir os objetivos descritos.

Para facilitar eu comecei a fazer uma tradução dos primeiros passos da inicialização:
https://docs.google.com/document/d/1WLipOaE--jFkOI6jX4eipKXxGEpwsk2_z2TWPUw-_xI/edit

**Comment by JonathanRufino** [comment]
- [x] Identificar as principais necessidades de negócios que geram motivos para se fazer um programa de melhoria de processo de software.

No contexto ao qual este trabalho está sendo executada (disciplina de graduação) o programa de melhoria de processo de software deve levar em consideração não apenas as características associadas ao desenvolvimento de software, mas também características de um ambiente de ensino e aprendizado.

Com isso foram identificadas as necessidades de negócio para a elaboração de um PSI e estão listadas a seguir:

**1. Avaliação e acompanhamento da participação dos alunos**

Como os grupos da disciplina são formados por muitos alunos, aproximadamente 10, é necessário estabelecer um processo que permita realizar o acompanhamento da participação dos membros de cada equipe nas suas devidas atribuições

**2. Garantia da entrega do produto solicitado**

A avaliação dos alunos está diretamente associada à entrega do produto de software e atividades associadas (desenvolvimento, processo e qualidade). Sendo assim, também é imprescindível definir um processo que auxilie os alunos na obtenção dos resultados esperados

**3. Controle e Acompanhamento do Projeto**

As diferentes equipes devem ser capazes de acompanhar o status do projeto sem que haja uma comunicação direta entre as equipes. Para isso devem ser estabelecidas atividades e ferramentas que possibilitem o acompanhamento do status do projeto e das atividades que estão sendo realizadas por outras equipes.

**Comment by JonathanRufino** [comment]
Não entendi se o programa de melhoria é definido aqui, ou se na verdade essa tarefa está misturada com a #33

**Comment by maugustoo** [comment]
Então, em tese as tarefas são feita paralelamente e ao fim das issues #32, #33 e #34 teremos a proposta de melhoria inicial. Mas o objetivo dessa issue é o que as tarefas definem. Na issue #33 vamos usar os insumes desta, que fará parte da proposta de melhoria.
