### ISSUE TITLE
Criar plano de comunicação

### ISSUE THREAD

**Issue by maugustoo** [UnbFeelings/unb-feelings-docs#34]
O objetivo dessa issue é criar um plano de comunicação que contenha dados de como será feito a comunicação entre os níveis organizacionais e dentro dos níveis organizacionais.

Tarefas:

- [x] Descrever como será feita a comunicação com a alta gerência
- [x] Descrever como será feita a comunicação entre os grupos de trabalho
- [x] Descrever como será feita a comunicação dentro dos grupos.

**Comment by maugustoo** [comment]
É interessante ler a fase 1.4 do modelo ideal, que descreve alguns passos para se conseguir atingir os objetivos descritos.

Para facilitar eu comecei a fazer uma tradução dos primeiros passos da inicialização:
https://docs.google.com/document/d/1WLipOaE--jFkOI6jX4eipKXxGEpwsk2_z2TWPUw-_xI/edit

**Comment by freemanpivo** [comment]
O plano de comunicação está desenvolvido nesse link: [Plano de Comunicação](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Plano-de-Comunica%C3%A7%C3%A3o)
