### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by Matheusss03** [UnbFeelings/unb-feelings-docs#36]
O link do SLACK será disponibilizado nessa issue.

@UnbFeelings/apolo @UnbFeelings/athena @UnbFeelings/themis  @UnbFeelings/alta-gerencia

**Comment by JonathanRufino** [comment]
Link para acesso ao Slack

https://join.slack.com/t/unbfeelings/shared_invite/enQtMzU5OTQ0ODgxNzYxLTQzMGM4Zjg5NGU0Nzc5YjkwOThjYzY3NmJiYzNkYzVlOThhNDhhNjkwNjBmZTgwZWQyNWNiMTZmOGM0MTEyNjk

**Comment by AllanNobre** [comment]
ENTREM NO SLACK, POR FAVOR! @UnbFeelings/apolo @UnbFeelings/athena

**Comment by freemanpivo** [comment]
Os canais de comunicação foram criados e alguns membros foram adicionados.

Falta os integrantes de desenvolvimento e a professora entrarem no slack. O *LINK* está disponível no comentário acima.

@UnbFeelings/apolo @UnbFeelings/athena @UnbFeelings/alta-gerencia

**Comment by freemanpivo** [comment]
Esqueci de dizer que não tem controle nas wikis dos membros que estão atualmente no desenvolvimento, por favor, necessito dessa lista de nomes para adicionar no canal correto.
