### ISSUE TITLE
Criar template para resultado de métricas por sprint

### ISSUE THREAD

**Issue by Rdlenke** [UnbFeelings/unb-feelings-docs#39]

**Comment by Rdlenke** [comment]
O template pode ser encontrado [aqui](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Template-para-Resultados-de-Coleta-de-M%C3%A9tricas-por-Sprint).

**Comment by AllanNobre** [comment]
Template revisado! Está tudo correto!
