### ISSUE TITLE
Métricas do GQM incompletas

### ISSUE THREAD

**Issue by joaopaulonsoares** [UnbFeelings/unb-feelings-docs#4]
Existem diversas métricas como, por exemplo, a definida no tópico _4.2.1.1.1 Nº de features por testes de aceitação_ que não tem sua descrição realizada.Elas serão utilizadas?

**Comment by MatheusRich** [comment]
[Corrigido](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo-de-Garantia-da-Qualidade)!
