### ISSUE TITLE
[Não conformidade] - Plano de medição - Auditoria 12/05/2018

### ISSUE THREAD

**Issue by VictorDeon** [UnbFeelings/unb-feelings-docs#42]
Auditoria realizada dia: 12/05/2018 por Victor Arnaud
Link: https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-do-plano-de-medi%C3%A7%C3%A3o-2

#### Não conformidade:

O plano de medição contêm o planejamento das coletas? O planejamento das coletas não foi encontrada na documentação.

Prazo: 15/05/2018

**Comment by joaopaulonsoares** [comment]
@VictorArnaud Acho que essa data aí tá errada

**Comment by VictorDeon** [comment]
ops kkk vlw quando solucionar o mesmo manda o link aqui

**Comment by VictorDeon** [comment]
Galera além do template das coletas de métricas o plano de medição deve especificar quando as métricas deve ser coletadas, ou seja, seu planejamento, no caso por sprint, ou por release, sei la ^^ só uma dica.

**Comment by Rdlenke** [comment]
@VictorArnaud No caso, seria um planejamento do estilo "as métricas ABC vão ser coletadas na Sprint 1", ou seria o momento dentro do processo onde a coleta é feita? 

Uma outra dúvida: caso seja um planejamento de quais métricas serão coletadas em qual sprint, não tem problema ser um planejamento de sprint a sprint, ao invés de ser um pra todas as sprints, certo?

Muito obrigado.

**Comment by VictorDeon** [comment]
Não, acho que o momento dentro do processo onde a coleta é feita é o suficiente, por exemplo, ao final das sprints é coletado as metricas de código, ao final do release é coletado ... não precisa especificar qual a métrica.

**Comment by Rdlenke** [comment]
Beleza. Atualizei o [plano de medição][plano de medição] com uma seção pra esse planejamento. Caso não seja bem isso, pode me falar que eu tento corrigir de outra maneira.

[plano de medição]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Plano-de-Medi%C3%A7%C3%A3o#4-planejamento-das-coletas

**Comment by VictorDeon** [comment]
Ta massa
