### ISSUE TITLE
Barreiras encontradas para realização de recomendações na fase de diagnóstico do modelo IDEAL

### ISSUE THREAD

**Issue by fabiolamfleury** [UnbFeelings/unb-feelings-docs#44]
Devido a falhas no mapeamento do estado atual do processo, há entraves para realizar recomendações de mudanças

**Comment by fabiolamfleury** [comment]
# Qualidade

Observando o que foi documentado como [estado atual](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Estado-Atual#processo-de-medi%C3%A7%C3%A3o-e-an%C3%A1lise) acredita-se que não engloba o que foi documentado no [estado desejado](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Estado-Desejado#2-qualidade)


* Template de métricas não está escrito como algo definido no processo de desejado;
* A estruturação de tópicos sendo divididos nos diferentes níveis de GQM não é o que deve ser mapeado para a definição do processo;
* Existe uma ênfase nos artefatos, além disso, o estado desejado define fases, atividades e papéis, o que não foi refletido no estado atual mapeado.

Sendo assim, propõe-se uma nova estruturação e mapeamento do estado atual:

### Fase de planejamento
* **Parcialmente Definido**
 Observa-se no processo de medição e análise uma fase de planejamento de medições, porém ele não possui detalhamentos que possam colocá-lo como adequado, exemplifica-se isso pela ausência de treinamentos e definição de levantamento de objetivos de negócio.

### Fase de definição
* **Não Definido**
 A fase de definição, onde são documentados objetivos,  folha de abstração, questões e métricas, não fica explicita no processo, nem é definido que estes artefatos devem existir.

### Fase de coleta de dados
* **Parcialmente Definido**
A fase de coleta de dados não está detalhada, não possuindo o artefato formulário de coleta de dados como saída, ou qualquer saída, apesar de utilizar o documento de análise como entrada, como o definido.
 
### Fase de interpretação de dados
* **Parcialmente Definido**
Existe no processo a definição de uma fase de análise de métricas, porém embora seja a equipe de processo que fica responsável pela realização do feedback, a equipe de desenvolvimento também deve participar desta fase.

### Divisão de papéis GQM
* **Parcialmente Definido**
Segundo o que está [aqui](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Plano-de-Medi%C3%A7%C3%A3o#2-pap%C3%A9is-e-responsabilidades-no-processo-de-medi%C3%A7%C3%A3o) os papéis definidos não seguem as recomendações do GQM. Conforme definido no estado desejado, a equipe de GQM(que foi  transferida, no nosso contexto, para equipe de processo é responsável pela parte mais gerencial do processo de medição e análise, enquanto a equipe de desenvolvimento é responsável pela coleta.

**Comment by Ronyell** [comment]
# Requisitos

Com base na análise dos GAP's  que se encontra no artefato [estado atual](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Estado-Atual#processo-de-medi%C3%A7%C3%A3o-e-an%C3%A1lise), foi constatado que este não engloba o que foi definido no [estado desejado](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Estado-Desejado#2-qualidade).  



Portanto, a partir do que foi definido no estado desejado, alguns dos pontos que teriam que ser considerados para uma análise mais completa relacionada aos requisitos do projeto são:

### Classificação dos Requisitos:
  * **Não Definido**

A classificação dos requisitos em  requisitos **funcionais** e **não funcionais** foi definida no [estado desejado](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Estado-Desejado#31-modelo), e essa característica não foi analizada. Com base no processo definido, não foi possível encontrar nada que se possa estar relacionado a esse fator.
Onde deveria ser encontrado?
* Planejamento da sprint e backlog da sprint (histórias de usuário e enablers ou similares)
* Planejamento da release e backlog da release (feature e enablers ou similares)
* Backlog do produto

### Rastreabilidade
* **Definido**

A rastreabilidade deve ser utilizada com um item de backlog mais genérico e um item de backlog mais específico, segundo o [estado desejado](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Estado-Desejado#313-n%C3%ADvel-organizacional-n%C3%ADvel-de-equipe) deve ser utilizado feature - história de usuário. No processo definido isso se encontra na atividade na atividade de [planejamento da sprint](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2112-planejar-sprint) com o mapeamento de feature em histórias no backlog da sprint.

###  Estimativa dos artefatos
* **Parcialmente Definido**


A estimativa das histórias está presente no [estado desejado](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Estado-Desejado#3121-estimativa-de-hist%C3%B3rias) e estão explicitadas no processo definido na atividade de [planejamento da sprint](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2112-planejar-sprint). No entanto, não são especificados a unidade média de medida específica (nem mesmo como política), recomenda-se que seja fibonacci e que essa pontuação seja feita por meio do planning poker.

### Priorização dos Itens
* **Parcialmente Definido**

A priorização dos itens deveria ser feito de acordo com o scrum segundo o [estado desejado](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Estado-Desejado#3121-estimativa-de-hist%C3%B3rias), e deve ser feito pelo product owner ou pelo cliente. A priorização fica explícita no [planejamento da sprint](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2112-planejar-sprint), no entanto não fica explícito como isso é feito nem mesmo em políticas.

### Gerenciamento de requisitos
* **Parcialmente Definido**

O gerenciamento dos requisitos, segundo o [scrum](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Estado-Desejado#12-pap%C3%A9is) que é usado no [safe](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Estado-Desejado#3111-cria%C3%A7%C3%A3o-e-gerenciamento-de-features), deve ser feito pelo product owner. A definição do gerenciamento das histórias está definido no [planejamento da sprint](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2112-planejar-sprint) mas não define o responsável. 

OBS: Em relação ao processo implementado, existem evidências que o acompanhamento dos requisitos não está sendo feito. Um exemplo claro que isso não está ocorrendo é a permanência do GitLab-CI como ferramenta de [integração contínua](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Plano-de-Ensino#unb-feelings-para-alunos-e-professores):
* REQT-09: Que seja realizado Integração Contínua utilizando GitLab CI/CD;
* REQT-10: Que seja realizado Entrega Contínua utilizando GitLab CI/CD;

**Comment by AllanNobre** [comment]
# Desenvolvimento

Observando o que foi documentado como [estado atual](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Estado-Atual) acredita-se que não engloba o que foi documentado no [estado desejado](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Estado-Desejado)

* O KanBan foi dado como completamente definido, contudo foi diagnosticado de forma absurdamente errada! De modo que não foi verificado se foi definido no processo, mas sim através de um documento que não tem sentido algum. Logo, deve-se verificar se o uso do KanBan foi explicitado no processo definido de alguma forma.

* Reunião diária: encontra-se com o status "Completamente Definido", na verdade deveria estar com "Parcialmente Definido" porque não está definido (timebox?) e local.
