### ISSUE TITLE
[Não Conformidade] - Relatório de Desempenho

### ISSUE THREAD

**Issue by santana-guilherme** [UnbFeelings/unb-feelings-docs#45]
A auditoria do relatório de desempenho foi executada para verificar se a atividade de medição e análise foi realizada. O resultado da auditoria pode ser acessado através da seguinte página: [Auditoria Relatório de Desempenho - Ciclo 2](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-do-Relat%C3%B3rio-de-Desempenho-Ciclo-2).  
## Descrição
O documento **Relatório de Desempenho** não foi elaborado.

### Recomendações
Tendo em vista que a coleta de métricas foi iniciada, basta terminar a coleta para possibilitar a elaboração do documento.

## Detalhes
**Autor:** Guilherme Sant'Ana
**Tipo:** Medição e Análise
**Prazo:** 24/05/18

**Comment by AllanNobre** [comment]
A Sprint acabou dia 15, acredito que o tempo para que as métricas tivessem sido colhidas foi deveras curto, de modo que essa auditoria poderia ser postergada um tempo a mais.

Outro fator agravante foi o fato de a tarefa de colher as métricas, ERRONEAMENTE PASSADA PARA A EQUIPE DE PROCESSO, deveria ser da equipe de desenvolvimento, essa afirmação é apoiada pelo  próprio GQM e segundo a própria lógica de coleta, onde os detentores da informação a respeito da métricas a serem colhidas são os próprios desenvolvedores do projeto.

Tendo em vista esse problema, o integrante da equipe de processo necessita sempre perguntar pra alguém de desenvolvimento sobre as métricas, estando sujeito a atrasos de respostas e boa vontade de pessoas que na verdade deveriam ser os coletores oficiais dessas métricas.

**Comment by AllanNobre** [comment]
Outra coisa, existe algum motivo para que a equipe de GQA não esteja seguindo o modelo de issue de não conformidade definido pela antiga equipe de GQA?

**Comment by santana-guilherme** [comment]
Concordo que o tempo de coleta de métricas é pequeno e que talvez seria melhor executar essa auditoria para mais adiante do projeto, ou alguma data em que seja mais viável para a equipe, pensando nisso deixei o prazo para dia 24 (sendo que o ciclo acaba dia 29 ). Como comentei com Marcelo(da equipe de processo) acredito que devido ao passo em que o planejamento da disciplina se encontra muitas auditorias estão sendo executadas prematuramente em relação ao andar do projeto. Levando isso em consideração, não encare a não conformidade como uma carência das atividades realizadas pela equipe de processo, ela é apenas o resultado da avaliação antecipada devido aos prazos da disciplina. 
Sobre a responsabilidade pela coleta de métricas, e a necessidade de algumas atividades definidas no processo, acredito que isso só será resolvido no ciclo de evolução do processo (posso estar enganado).
Quanto ao formato da issue, colocarei nos padrões estabelecidos pelo modelo :+1: .

**Comment by Rdlenke** [comment]
O relatório de desempenho da sprint 1 foi elaborado e pode ser encontrado no seguinte [zelda].

@GDSRS 

[zelda]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Relat%C3%B3rio-de-Desempenho-da-Sprint-1
