### ISSUE TITLE
[Não Conformidade] - Relatório de Desempenho Sprint 2

### ISSUE THREAD

**Issue by santana-guilherme** [UnbFeelings/unb-feelings-docs#49]
A auditoria do relatório de desempenho foi executada para verificar se a atividade de medição e análise foi realizada. O resultado da auditoria pode ser acessado através da seguinte página: [Auditoria Relatório de Desempenho sprint 2 - Ciclo 2](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-Relatório-de-Desempenho-Sprint-2-Ciclo-2).  
## Descrição
O documento **Relatório de Desempenho** não foi elaborado.

### Recomendações
Analisar as métricas existentes coletadas pela equipe de processo, e elaborar o documento

## Detalhes
**Autor:** Guilherme Sant'Ana
**Tipo:** Medição e Análise
**Prazo:** 28/05/18

**Comment by Rdlenke** [comment]
O [relatório de desempenho] da sprint 2 foi produzido.

@GDSRS 

[relatório de desempenho]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Relat%C3%B3rio-de-Desempenho-da-Sprint-2
