### ISSUE TITLE
Plano de Medição

### ISSUE THREAD

**Issue by Ronyell** [UnbFeelings/unb-feelings-docs#5]
Para cada iteração é realmente necessário a criação de um novo plano de medição?

Pelo processo definido, tudo parece que está sendo refeito a cada iteração, inclusive o plano de requisitos, isso é realmente preciso?

O processo de qualidade e o plano de medição estão na mesma página, seria mais indicado separar esses artefatos.

@UnbFeelings/process

**Comment by MatheusRich** [comment]
Olá @Ronyell (@UnbFeelings/gqa),

Não entendi sua dúvida. A cada iteração os documentos são apenas atualizados.

**Comment by Ronyell** [comment]
@MatheusRich, isso não ficou muito claro na descrição das atividades e nem no desenho do processo.

**Comment by MatheusRich** [comment]
Foi criada [uma seção](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Crit%C3%A9rios-de-aceita%C3%A7%C3%A3o-para-artefatos) com a descrição dos artefatos. Espero que esclareça.
