### ISSUE TITLE
Reformular Diagrama de Métricas de Qualidade

### ISSUE THREAD

**Issue by joaopaulonsoares** [UnbFeelings/unb-feelings-docs#50]
Reformular o diagrama na página: https://github.com/UnbFeelings/unb-feelings-docs/wiki/SEM-NOME
para que métricas mais condizentes com as mudanças efetuadas sejam definidas e coletadas. De acordo com feedback dado pela professora:

**Comment by joaopaulonsoares** [comment]
@joaopaulonsoares Vi essas aqui como possíveis para coleta agora. Algumas delas são pelo formulário, @ThiagoNogueira1  limpa la a planilha pra podermos mandar pros outros grupos

**Comment by thiagonf** [comment]
@joaopaulonsoares Vou limpar agora

**Comment by AllanNobre** [comment]
Feedback da Professora 30/05:
- [x] O Benefício **Satisfação dos Alunos** com suas duas métricas descendentes deve ser movido para a Necessidade **Avaliação e Acompanhamento da participação dos Alunos**;
- [x] O Benefício **Feedback da Metodologia Utilizada** deve ser removido junto a sua métrica descendente. Este irá ser refletido em uma métrica do Benefício **Satisfação dos Alunos**;
- [x] Do Benefício **Satisfação dos Alunos** as métricas descendentes devem ser:
   - **Satisfação com a Metodologia** (Substituindo a antiga métrica **Quantidade de alterações realizadas na metodologia**);
   - **Satisfação com o Desempenho na Disciplina** (Substituindo a antiga métrica **Desempenho Avaliado**);
   - **Satisfação com o Processo** (Nova Métrica);
   - A métrica **Sentimento Estudantil** foi diluída entre as métricas a cima;
- [x] Mudar métrica **Número de Erros Referentes a Folha de Estilo** para **Aderência aos Padrões de Código**;
- [x] Mudar métrica **Quantidade de Não-Conformidades** para **Aderência ao Processo**;
- [x] A métrica **Percentual de Métricas Coletadas** deve sumir do Benefício **Manutenibilidade**;
- [x] A métrica **Percentual de Métricas Coletadas** deve sumir do Benefício **Visão Macro do Projeto**, já que a métrica **Aderência ao Processo** no Benefício **Visão Macro do Projeto** será responsável por analisar se os processos de Desenvolvimento e Medição estão sendo seguidos de fato, de modo que a equipe de GQA deve fornecer a Quantidade de Não-Conformidades para que essa métrica de **Aderência ao Processo** seja calculada para os processos afetados pela melhoria;

OBS: Deve-se revisar a forma de coleta de todas as métricas para checar se estão corretas;
