### ISSUE TITLE
Backlog de Backlogs

### ISSUE THREAD

**Issue by Ronyell** [UnbFeelings/unb-feelings-docs#52]
### Épico 01- Apoio à um perfil
.....
#### Feature 01 (E01FE01) - Publicar Apoio
.....
#### Feature 02 (E01FE02) - Gerenciar Apoio
......
### Épico 02 - Bloqueio
......
#### Feature 01 (E02FE01) -  Bloquear perfil
......
#### Feature 02 (E02FE02) - Gerenciar perfis bloqueados
.....

**Comment by Ronyell** [comment]
@joaopaulonsoares Épico 01 e E01F01
@Ronyell E01F02 e Épico 02
@JonathanRufino  E02F01 e E02F02

**Comment by Ronyell** [comment]
Feature 02 (E01FE02) - Gerenciar Apoio
Essa feature tem como objetivo o gerenciamento dos apoios a um perfil. Portanto, permite que o dono do perfil visualize e exclua os apoios dados a ele.

Épico 02 (E02) - Bloqueio
<table>
<tr><td  colspan="2" align="center"><b>Declaração de posição prospectiva
</b></td></tr>
<tr><td>Para</td> <td>Os alunos registrados no aplicativo UnB Feelings</td></tr>
<tr><td>Que</td> <td>Recebem mensagens em apoio à sua expressão</td></tr>
<tr><td>O</td> <td>Bloqueio</td></tr>
<tr><td>É uma </td> <td> Funcionalidade</td></tr>
<tr><td>Que </td> <td>  Permite que o aluno bloqueie perfis de forma que se possa impedir possíveis abusos e agressões verbais</td></tr>
<tr><td>Diferente </td> <td> - </td></tr>
<tr><td>Nossa Solução </td> <td> A criação de uma funcionalidade que permite bloquear perfis    </td></tr>
<tr><td  colspan="2" align="center"><b>Escopo</b></td></tr>
<tr><td>Critérios de sucesso </td><td> O aluno deve ser capaz de bloquear, desbloquear e visualizar mensagens de histórico caso não tenha sido apagada. Os perfis envolvidos, tanto o que bloqueou quanto o que foi bloqueado, não devem visualizar em sua timeline postagens do outro aluno.</td></tr>
<tr><td>No escopo </td><td>Bloquear Perfil, Gerenciamento de bloqueio de perfis</td></tr>
<tr><td>Fora do escopo </td><td> Apoio à um perfil </td></tr>
<tr><td> Requisitos de Qualidade </td><td> - </td></tr>
</table>

**Comment by JonathanRufino** [comment]
Feature 01 (E02FE01) - Bloquear perfil

Essa feature tem como objetivo permitir que o usuário bloqueie outros usuários, impedindo a visualização de suas informações e que o usuário bloqueado possa interagir em sua timeline ou em suas publicações

Feature 02 (E02FE02) - Gerenciar perfis bloqueados

Essa feature tem como objetivo permite que o usuário gerencie os usuários que ele bloqueou, permitindo visualizar os usuários bloqueados e desbloqueá-los

**Comment by joaopaulonsoares** [comment]
Feature 01 (E01FE01) - Publicar Apoio
Essa feature tem como objetivo permitir a publicação de um apoio de um membro à. Portanto, permite que um membro do UnBFeelings preste apoio a outro membro do UnBFeelings.

Épico 01 (E01) - Apoio à um perfil
<table>
<tr><td  colspan="2" align="center"><b>Declaração de posição prospectiva
</b></td></tr>
<tr><td>Para</td> <td>Os alunos registrados no aplicativo UnB Feelings</td></tr>
<tr><td>Que</td> <td>Postam suas expressões</td></tr>
<tr><td>O</td> <td>Apoio à um perfil</td></tr>
<tr><td>É uma </td> <td> Funcionalidade</td></tr>
<tr><td>Que </td> <td>  Permite que um aluno preste apoio a outro por meio de mensagens em seu perfil.</td></tr>
<tr><td>Diferente </td> <td> - </td></tr>
<tr><td>Nossa Solução </td> <td> Criação de uma funcionalidade para prestar apoio.  </td></tr>
<tr><td  colspan="2" align="center"><b>Escopo</b></td></tr>
<tr><td>Critérios de sucesso </td><td> O aluno deve ser capaz de publicar apoio a outro estudante, assim como visualizar o apoio prestado por outros..</td></tr>
<tr><td>No escopo </td><td>Publicar apoio,visualizar apoio</td></tr>
<tr><td>Fora do escopo </td><td> - </td></tr>
<tr><td> Requisitos de Qualidade </td><td> - </td></tr>
</table>

**Comment by Ronyell** [comment]
## Épico 01
### Feature 01

#### (E01F01US01) - Eu, como usuário, desejo publicar em um perfil de um usuário para poder apoiar um perfil.

**Critérios de Aceitação**

- [ ] O usuário deve ser capaz de apoiar outro perfil de forma anônima.
- [ ] O usuário deve ser capaz de postar uma mensagem nesse perfil.

### Feature 02

#### (E01F02US01) - Eu, como usuário, desejo visualizar os apoios dados ao meu perfil para saber qual o feedback dos demais alunos para com meu sentimento.

**Critérios de Aceitação**

(Caixa de entrada)
- [ ] O usuário apoiado deve ser capaz de visualizar os apoios prestados a ele.
- [ ] Outros usuários não devem ser capazes de visualizar os apoios de outros perfis.

#### (E01F02US02) - Eu, como usuário, desejo visualizar os apoios que foram prestados através do meu perfil para visualizar os feedbacks que enviei aos outros alunos.

**Critérios de Aceitação**

(Caixa de saída)
- [ ] O usuário apoiado deve ser capaz de visualizar os apoios que ele prestou.
- [ ] Outros usuários não devem ser capazes de visualizar os apoios que um usuário específico prestou.

#### (E01F02US03) - Eu, como usuário, desejo excluir apoio prestado à mim por outro perfil para 

**Critérios de Aceitação**

- [ ] Com base na visualização dos apoios, o usuário deve ser capaz de excluir um apoio do seu perfil.

**Comment by Ronyell** [comment]
## Épico 02
### Feature 01

#### (E02F01US01) - Eu, como usuário, desejo bloquear perfil de um outro usuário para evitar receber mensagens indesejadas de um usuário em específico.

**Critérios de Aceitação**

- [ ] Um usuário deve ser capaz de bloquear um perfil de um outro usuário em um apoio feito por um usuário.
Exemplo:
![image](https://user-images.githubusercontent.com/20937537/41513130-474c1aa6-726d-11e8-9703-c6ff39e71e47.png)

- [ ] Deve existir uma confirmação para bloqueio de usuários

Dado um usuário X que bloqueou um usuário Y:

- [ ] O usuário X não deve ser capaz de acessar informações referentes ao usuário Y.
- [ ] O usuário Y não deve ser capaz de acessar informações referentes ao usuário X.

### Feature 02

#### (E02F02US01) - Eu, como usuário, desejo visualizar uma lista de usuários que bloqueei para poder desbloquear um usuário já bloqueado.

**Critérios de Aceitação**

- [ ] O usuário deve ser capaz de visualizar todos os usuários que foram bloqueados por ele.

#### (E02F02US02) - Eu, como usuário, desejo desbloquear um usuário que foi bloqueado anteriormente para retomar a interação com ele.

**Critérios de Aceitação**

- [ ] O usuário deve ser capaz de desbloquear um usuário.
- [ ] O usuário deve ser alertado do desbloqueio de outro usuário.

Dado um usuário X que desbloqueou um usuário Y:

- [ ] O usuário X deve ser capaz de acessar informações referentes ao usuário Y.
- [ ] O usuário Y deve ser capaz de acessar informações referentes ao usuário X.

**Comment by AllanNobre** [comment]
As histórias derivadas das Features foram documentadas neste [zelda](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Backlog-de-Hist%C3%B3rias---Release-3).
