### ISSUE TITLE
Analisar Requisitos - Participantes

### ISSUE THREAD

**Issue by AllanNobre** [UnbFeelings/unb-feelings-docs#6]
Acredito que nesta [atividade](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2212-analisar-requisitos) do processo existe um erro a respeito dos Participantes.

Aparentemente o cliente não participa dessa atividade, contudo foi alocado como um dos participantes. Um dos critérios da auditoria dessa atividade englobará a participação do cliente, caso ele não esteja presente na execução desta, será uma não conformidade.

Caso tenha sido realmente um erro na descrição da atividade, responda essa issue corrigindo o problema para que o critério da auditoria seja, também, modificados.

@UnbFeelings/process

**Comment by MatheusRich** [comment]
Olá @AllanNobre (@UnbFeelings/gqa),

Atualizei a [descrição](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2212-analisar-requisitos), realmente era um erro. Algo mais?

**Comment by AllanNobre** [comment]
Suave, Obrigado!
