### ISSUE TITLE
Métrica de endpoints do GQM

### ISSUE THREAD

**Issue by fabiolamfleury** [UnbFeelings/unb-feelings-docs#8]
No GQM de vocês, existe uma métrica documentada "Percentual de endpoints documentados) [url](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo-de-Garantia-da-Qualidade#122-garantir-a-manuteabilidade) porém na parte de plano de análise [aqui](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo-de-Garantia-da-Qualidade#12215-percentual-de-endpoints-testados) está como percentual de endpoints testados, não consegui entender muito bem essa métrica

**Comment by fabio1079** [comment]
Obrigado por levantar essa diferença nos nomes.

Quanto a métrica, em suma é o quanto os testes cobrem a quantidade de endpoints da API, dando assim uma maior segurança no desenvolvimento e manutenção da API como um todo.

Sobre a diferença nos nomes, é por que originalmente seria quantos endpoints estão devidamente documentos(no swagger ou ferramenta similar). Porem não conseguimos chegar a um consenso sobre como obter essa métrica, logo optou-se por usar cobertura de testes nos endpoints. Infelizmente passou-se despercebido essa diferença na na wiki.

**Comment by fabio1079** [comment]
Obrigado por levantar essa diferença nos nomes.

Quanto a métrica, em suma é o quanto os testes cobrem a quantidade de endpoints da API, dando assim uma maior segurança no desenvolvimento e manutenção da API como um todo.

Sobre a diferença nos nomes, é por que originalmente seria quantos endpoints estão devidamente documentos(no swagger ou ferramenta similar). Porem não conseguimos chegar a um consenso sobre como obter essa métrica, logo optou-se por usar cobertura de testes nos endpoints. Infelizmente passou-se despercebido essa diferença na na wiki.

**Comment by fabiolamfleury** [comment]
Beleza, obrigada pelo esclarecimento!
